### ISSUE TITLE
Generic verify function

### ISSUE THREAD

**Issue by TomAugspurger** [TomAugspurger/engarde#4]
The "built-in" functions are convenient, but maybe you want to add your own check quickly.

Give a function that takes a DataFrame, does it's operation, and asserts it's Truthiness.

```python
def verify(df, func, *args, **kwargs):  # defined in engarde
    assert func(df, *args, **kwargs)
    return df

df.pipe(verify, lambda x: x > 0)

```

The above naive implementation would probably fail since the truth of Series([True, True]) is ambiguous. Is it too magic to automatically reduce that down to a `True` with a `np.all`?

Should also make a `decoratize` function that makes arbitrary functions usable in decorators.

**Comment by jnmclarty** [comment]
I do think it's "too magic", it should be more explicit.  I think you can get that done, via a solid naming convention.  Consider,  "verify_all", "verify_any".  Might do it.

But, bigger picture here, this is where I'm stuck.  I sat down tonight, and thought a bit harder about both the API, and slicing, and the plans for the kinds of tests I want/plan to contribute.  I'm going to add some notes to my other PR...

**Comment by TomAugspurger** [comment]
Great thanks.

I promise to be a better maintainer starting next week :wink: Real-life stuff has taken priority the last couple weeks, but I want to get this polished and usable before PyData Seattle at the end of July.
