### ISSUE TITLE
Pushing update to pypi

### ISSUE THREAD

**Issue by drorata** [TomAugspurger/engarde#45]
It seems like the current HEAD on master (https://github.com/TomAugspurger/engarde/commit/8d19015bb0fd45cfd5a40306b8bc42eb045a1420) is not pushed to pypi. For example there's no `columns` keyword argument for `none_missing`. Why is that?

**Comment by TomAugspurger** [comment]
Just haven't done a release in a while. I'm a bit backed up at the moment, though I can try to find some time this week.

**Comment by drorata** [comment]
I thought something is wrong with me, as it is documented and in the code base, but the local installation didn't reflect it. Would be nice! It's a really nice piece of tool.

**Comment by drorata** [comment]
Any update on this? Can I offer help?

**Comment by TomAugspurger** [comment]
Done in https://github.com/TomAugspurger/engarde/commit/022cfa3a8aab7a227dc10c24647d5f68ade15184

https://pypi.org/project/engarde/0.4.0/
