### ISSUE TITLE
Provide message along with raising AssertionError?

### ISSUE THREAD

**Issue by ianozsvald** [TomAugspurger/engarde#7]
Hi Tom. I've just spent 5 minutes with engarde, cheers. One immediate question, if I use `engarde.checks.none_missing(my_df)` and I have a null in the dataframe, it raises `assert not df[columns].isnull().any().any()` but the stack trace is hard to read. Might you add a note to the assert, maybe something like:
`assert not df[columns].isnull().any().any(), "This DataFrame contains at least one null value"`

Thanks for helping me to sanity check my df->sklearn processing :-)

**Comment by TomAugspurger** [comment]
Thanks. Better failure messages are pretty high on my todo list.

I've mostly put it off thinking I'd try something like what [py.test](http://pytest.org/latest/) does. When I looked last week though I found out they start manipulating the AST, which would be way to involved for this little project :)

I'll get better messages sometime later this week most likely.
